#!/usr/bin/env python3
"""Turns web/index.html into PowerScope/web_index.h (gzip bytes in PROGMEM).

Usage:   python tools/embed_web.py
         python tools/embed_web.py path/to/index.html path/to/web_index.h
Run it again after every edit of the page, then upload the sketch again.
"""
import gzip, os, sys, zlib

here = os.path.dirname(os.path.abspath(__file__))
src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(here, "..", "web", "index.html")
dst = sys.argv[2] if len(sys.argv) > 2 else os.path.join(here, "..", "firmware", "PowerScope", "web_index.h")

raw = open(src, "rb").read()
gz = gzip.compress(raw, compresslevel=9, mtime=0)
etag = "%08x" % (zlib.crc32(raw) & 0xFFFFFFFF)

lines = []
for k in range(0, len(gz), 20):
    lines.append("  " + ",".join("0x%02x" % b for b in gz[k:k + 20]) + ",")

with open(dst, "w", newline="\n") as f:
    f.write("// AUTO-GENERATED by tools/embed_web.py from web/index.html - do not edit.\n")
    f.write("#pragma once\n#include <Arduino.h>\n\n")
    f.write("// %d bytes raw, %d bytes gzip\n" % (len(raw), len(gz)))
    f.write("const size_t INDEX_HTML_GZ_LEN = %d;\n" % len(gz))
    f.write('#define INDEX_HTML_ETAG "\\"%s\\""\n' % etag)
    f.write("const uint8_t INDEX_HTML_GZ[] PROGMEM = {\n")
    f.write("\n".join(lines) + "\n};\n")

print("wrote %s: %d bytes raw -> %d bytes gzip (etag %s)" % (os.path.basename(dst), len(raw), len(gz), etag))
